Name:           ros-melodic-abb-irb6640-support
Version:        1.3.1
Release:        1%{?dist}
Summary:        ROS abb_irb6640_support package

Group:          Development/Libraries
License:        Apache2
URL:            http://wiki.ros.org/abb_irb6640_support
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-abb-driver
Requires:       ros-melodic-joint-state-publisher
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-rviz
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roslaunch >= 1.9.55

%description
ROS-Industrial support for the ABB IRB 6640 (and variants). This package
contains configuration data, 3D models and launch files for ABB IRB 6640
manipulators. This currently includes the IRB 6640-185/2.8m (6640-185) only.
Joint limits and max joint velocities are based on the information in the ABB
IRB 6640 technical data sheet (Version: 3HAC 028284-001 Rev. N). All urdfs /
xacros are based on the default motion and joint velocity limits, unless noted
otherwise (ie: no support for high speed joints, extended / limited motion
ranges or other options). Before using any of the configuration files and / or
meshes included in this package, be sure to check they are correct for the
particular robot model and configuration you intend to use them with.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Sep 18 2019 Levi Armstrong (Southwest Research Institute) <levi.armstrong@swri.org> - 1.3.1-1
- Autogenerated by Bloom

