Name:           ros-indigo-abb-irb6600-support
Version:        1.2.1
Release:        0%{?dist}
Summary:        ROS abb_irb6600_support package

Group:          Development/Libraries
License:        Apache2
URL:            http://ros.org/wiki/abb_irb6600_support
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-abb-driver
Requires:       ros-indigo-joint-state-publisher
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-rviz
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roslaunch

%description
ROS-Industrial support for the ABB IRB 6600 (and variants). This package
contains configuration data, 3D models and launch files for ABB IRB 6600
manipulators. This currently includes the base model. Joint limits and max joint
velocities are based on the information in the ABB data sheets. All URDFs /
XACROs are based on the default motion and joint velocity limits, unless noted
otherwise (ie: no support for high speed joints, extended / limited motion
ranges or other options). Before using any of the configuration files and / or
meshes included in this package, be sure to check they are correct for the
particular robot model and configuration you intend to use them with. The
unqualified IRB 6400 model will be removed in ROS-Lunar, please use the
abb_irb6640_support as a replacement.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Mar 27 2017 Levi Armstrong (Southwest Research Institute) <levi.armstrong@swri.org> - 1.2.1-0
- Autogenerated by Bloom

* Sat Jun 06 2015 Shaun Edwards (Southwest Research Institute) <sedwards@swri.org> - 1.2.0-0
- Autogenerated by Bloom

* Tue Apr 07 2015 Shaun Edwards (Southwest Research Institute) <sedwards@swri.org> - 1.1.9-0
- Autogenerated by Bloom

